services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./dbinit.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=Mail.12345

  postfixadmin:
    image: postfixadmin:fpm
    container_name: postfixadmin
    restart: unless-stopped
    volumes:
      - ./www/postfixadmin:/var/www/html
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: db
      POSTFIXADMIN_DB_USER: postfixadmin
      POSTFIXADMIN_DB_NAME: postfixadmin
      POSTFIXADMIN_DB_PASSWORD: Mail.12345
      POSTFIXADMIN_SMTP_SERVER: postfix
      POSTFIXADMIN_SMTP_PORT: 25
      POSTFIXADMIN_ENCRYPT: md5crypt

  dovecot:
    image: dovecot/dovecot:latest
    container_name: dovecot
    restart: unless-stopped
    ports:
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    volumes:
      - ./data/mail:/srv/mail
      - ./dovecot:/etc/dovecot

  postfix:
    image: postfix:latest
    container_name: postfix
    restart: unless-stopped
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - ./postfix:/etc/postfix

  roundcubemail:
    image: roundcube/roundcubemail:latest-fpm
    container_name: roundcubemail
    restart: unless-stopped
    volumes:
      - ./www/roundcubemail:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=db
      - ROUNDCUBEMAIL_DB_NAME=roundcubemail
      - ROUNDCUBEMAIL_DB_PASSWORD=Mail.12345
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://dovecot
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://postfix

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      # If you need SSL connection
      - 443:443
    volumes:
      - ./www:/var/www/html
      # Provide a custom nginx conf
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      # If you need SSL connection, you can provide your own certificates
      - ./data/certs:/certs
    #environment:
      #- NGINX_HOST=localhost  # set your local domain or your live domain
      #- NGINX_PHP_CGI=roundcubemail:9000  # same as roundcubemail container name

### Optional: add a full mail server stack to use with Roundcube like https://github.com/docker-mailserver/docker-mailserver
#   mailserver:
#     image: mailserver/docker-mailserver:latest
#     hostname: mail.example.org
#     ...  # for more options see https://github.com/docker-mailserver/docker-mailserver#examples
